name: Build PostgreSQL from Source with Version-Specific Patches

on:
  schedule:
    - cron: '0 12,0 * * *'
  push:
    branches:
      gh_actions  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: ["15.10", "16.6", "17.2"] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Build PostgreSQL ${{ matrix.pg_version }}
        run: docker build --build-arg PG_VERSION=${{ matrix.pg_version }} -t custom-postgres:${{ matrix.pg_version }} .

      - name: Run PostgreSQL Container
        run: docker run --rm -d -p 5432:5432 --name custom-postgres custom-postgres:${{ matrix.pg_version }} postgres --version

      - name: Wait for PostgreSQL to be Ready
        run: |
             until pg_isready -h localhost -p 5432 -U postgres; do
             echo "Waiting for PostgreSQL to be ready..."
             sleep 2
             done
             echo "PostgreSQL is ready!"


      - name: Verify Database is Live
        run: |
          psql -h localhost -U postgres -d postgres -c 'SELECT 1;'

      
