name: Docker tests
run-name: ${{ github.actor }} is running the test schedules.

on:
  push:
    branches:
      - gh_actions
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-scripts:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        pgver: [15, 16, 17]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Configure Passwordless Sudo
      run: |
        echo "ALL ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/passwordless
        sudo chmod 0440 /etc/sudoers.d/passwordless

    - name: Verify Passwordless Sudo
      run: |
        sudo whoami
        sudo pwd

    - name: Configure Passwordless SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -q -N ""
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys

    - name: Verify Passwordless SSH
      run: |
        ssh -o StrictHostKeyChecking=no localhost "echo passwordless SSH configured"

    - name: Install System Dependencies
      run: |
        sudo apt-get update &&
        sudo apt-get install -y \
          build-essential \
          libreadline-dev \
          zlib1g-dev \
          bison \
          flex \
          curl \
          ca-certificates \
          gcc \
          git \
          wget \
          libicu-dev \
          && sudo rm -rf /var/lib/apt/lists/*

    - name: Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install python-dotenv psycopg2 psycopg

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t spock docker/

    - name: Create Docker Network
      run: |
        docker network create pg_network || true

    - name: Run Docker Container
      run: |
        docker run -d --name spock --network pg_network spock

    - name: Wait for SSH to Start
      run: |
        echo "Waiting for SSH to start..."
        for i in {1..10}; do
          if docker exec spock pgrep sshd > /dev/null; then
            echo "SSHD is running!"
            exit 0
          fi
          echo "SSHD not ready, retrying..."
          sleep 2
        done
        echo "SSHD failed to start!"
        exit 1

    - name: Verify Container User
      run: |
        docker exec spock whoami

    - name: Install System Dependencies Inside the Container
      run: |
        docker exec -u root spock bash -c "
          apt-get update && \
          apt-get install -y \
            build-essential \
            libreadline-dev \
            zlib1g-dev \
            bison \
            flex \
            curl \
            ca-certificates \
            gcc \
            git \
            wget \
            libicu-dev && \
          rm -rf /var/lib/apt/lists/*
        "

    - name: Create PostgreSQL Directories
      run: |
        sudo mkdir -p /var/lib/postgresql/data
        sudo chown -R postgres:postgres /var/lib/postgresql

    - name: Set PostgreSQL Environment Variables
      run: |
        echo 'export PATH="/usr/local/pgsql/bin:$PATH"' >> $GITHUB_ENV
        echo 'export PGDATA="/var/lib/postgresql/data"' >> $GITHUB_ENV

    - name: Ensure Passwordless Sudo for postgres
      run: |
        echo "postgres ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/postgres
        sudo chmod 0440 /etc/sudoers.d/postgres
        sudo usermod -aG sudo postgres  # Add postgres user to sudo group

    - name: Clone Postgres Repo and List Files
      run: |
        docker exec -u postgres spock bash -c "
          sudo apt-get update && sudo apt-get install -y git && \
          git clone https://github.com/postgres/postgres.git /home/postgres/postgres-source && \
          cd /home/postgres/postgres-source && \
          ls -la
        "

    - name: Verify Cloned Postgres Repository
      run: |
        docker exec -u postgres spock ls -la /home/postgres/postgres-source

    - name: List All Available Tags in Cloned Repository
      run: |
        docker exec -u postgres spock bash -c "
          cd /home/postgres/postgres-source && \
          git fetch --tags && \
          git tag -l
        "

    - name: Display Current PostgreSQL Version from Matrix
      run: |
        echo "Current matrix.pgver: ${{ matrix.pgver }}"
        whoami
        pwd

    - name: Checkout Latest PostgreSQL Tag for matrix.pgver
      run: |
        docker exec -u postgres spock bash -c "
          cd /home/postgres/postgres-source && \
          git fetch --tags && \
          MATRIX_PGVER=${{ matrix.pgver }} && \
          LATEST_TAG=\$(git tag -l \"REL_\${MATRIX_PGVER}*\" | grep -Eo 'REL_[0-9]+_[0-9]+(_[0-9]+)?' | sort -V | tail -n 1) && \
          git checkout \$LATEST_TAG && \
          echo \"Checked out tag: \$LATEST_TAG\"
        "

    - name: Clone spock-private and list files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker exec -u postgres spock bash -c "
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/pgedge/spock-private.git /home/postgres/spock-private && \
          cd /home/postgres/spock-private && \
          ls -la
        "

    - name: Apply PostgreSQL Patches for matrix.pgver
      run: |
        docker exec -u postgres spock bash -c '
          cd /home/postgres/postgres-source && \
          PATCH_DIR="/home/postgres/spock-private/patches" && \
          MATRIX_PGVER="${{ matrix.pgver }}" && \
          POSTGRES_DIR="/home/postgres/postgres-source" && \
          
          echo "Patch Directory: $PATCH_DIR"
          echo "PostgreSQL Version: $MATRIX_PGVER"
          echo "Postgres Source Directory: $POSTGRES_DIR"
          
          ls $PATCH_DIR
          ls $PATCH_DIR/pg${MATRIX_PGVER}-*.diff

          if compgen -G "$PATCH_DIR/pg${MATRIX_PGVER}-*.diff" > /dev/null; then
            for PATCH_FILE in $PATCH_DIR/pg${MATRIX_PGVER}-*.diff; do
              echo "Applying patch: $PATCH_FILE"
              patch -p1 < "$PATCH_FILE" && echo "Successfully applied: $PATCH_FILE" || { echo "Failed to apply: $PATCH_FILE"; exit 1; }
            done
          else
            echo "No patches found for pg$MATRIX_PGVER."
          fi
        '

    - name: Configure, Build, and Install PostgreSQL
      run: |
        docker exec -u postgres spock bash -c "
          cd /home/postgres/postgres-source && \
          ./configure --prefix=/usr/local/pgsql --without-icu && \
          make -j\$(nproc) && \
          sudo make install
        "

    - name: Create the PostgreSQL Data Directory
      run: |
        docker exec -u root spock bash -c "
          mkdir -p /var/lib/postgresql/data && \
          chown -R postgres:postgres /var/lib/postgresql && \
          chmod 700 /var/lib/postgresql/data
        "

    - name: Initialize the cluster and start the postmaster
      run: |
        docker exec -u postgres spock bash -c "
          export PGDATA=/var/lib/postgresql/data && \
          if [ ! -f \$PGDATA/PG_VERSION ]; then
            echo 'Initializing PostgreSQL database...'
            /usr/local/pgsql/bin/initdb -D \$PGDATA
          fi && \
          echo 'Starting PostgreSQL postmaster...' && \
          /usr/local/pgsql/bin/postmaster -D \$PGDATA > /home/postgres/postgres.log 2>&1 &
        "

    - name: Locate pg_config and Update PATH
      run: |
        docker exec -u postgres spock bash -c "
          PG_CONFIG_PATH=\$(find /usr/local/pgsql -type f -name pg_config | head -n 1) && \
          if [ -z \"\$PG_CONFIG_PATH\" ]; then
            echo 'Error: pg_config not found' && exit 1
          fi && \
          PG_BIN_DIR=\$(dirname \"\$PG_CONFIG_PATH\") && \
          echo \"Found pg_config in: \$PG_BIN_DIR\" && \
          echo \"export PATH=\$PG_BIN_DIR:\$PATH\" >> ~/.bashrc && \
          export PATH=\$PG_BIN_DIR:\$PATH && \
          echo \"pg_config location successfully added to PATH\"
        "

    - name: Put your test cases here
      run: |
        echo "Current User: $(whoami)" > latest.log
        echo "Current Path: $(pwd)" >> latest.log
        cat latest.log

    - name: Upload Log File as Artifact
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: latest-log-${{ matrix.pgver }}
        path: latest.log

