name: Build PostgreSQL from Source with Version-Specific Patches

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [13, 14, 15, 16] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build PostgreSQL ${{ matrix.pg_version }}
        run: docker build --build-arg PG_VERSION=${{ matrix.pg_version }} -t custom-postgres:${{ matrix.pg_version }} .

      - name: Run PostgreSQL Version Check for ${{ matrix.pg_version }}
        run: docker run --rm custom-postgres:${{ matrix.pg_version }} postgres --version
