name: Build PostgreSQL from Source with Version-Specific Patches

on:
  schedule:
    - cron: '0 12,0 * * *'
  push:
    branches:
      gh_actions  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_ver: ["15", "16", "17"] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Define Dockerfile name
        id: set-dockerfile
        run: |
          DOCKERFILE_NAME="Dockerfile${{ matrix.pgver }}"
          echo "DOCKERFILE_NAME=$DOCKERFILE_NAME" >> $GITHUB_ENV

      - name: Build PostgreSQL ${{ matrix.pgver }}
        run: |
          docker build --build-arg PG_VERSION=${{ matrix.pgver }} -t custom-postgres:${{ matrix.pgver }} -f $DOCKERFILE_NAME .

      - name: Run PostgreSQL Container
        run: |
          docker run --rm -d -p 5432:5432 --name custom-postgres-${{ matrix.pgver }} custom-postgres:${{ matrix.pgver }}

      - name: Check Docker Container Status
        run: docker ps -a
      
      - name: Wait for PostgreSQL to be ready
        run:
          timeout 90s bash -c 'until docker exec custom-postgres pg_isready ; do sleep 5 ; done'
